### ISSUE TITLE
Bug: OpenshiftConfigBuilder produces values erroneous string values containing "null" 

### ISSUE THREAD

**Issue by geoand** [ap4k/ap4k#126]
If one tries to do something like:

```
    final OpenshiftConfigBuilder openshiftConfigBuilder = OpenshiftConfigAdapter.newBuilder(new HashMap());
    System.out.println(openshiftConfigBuilder.build().getGroup());
```

the result of the print statement will be: `"null"` instead of something like a proper `null` or an empty string.
This prevents `ApplyProjectInfo` from properly applying the project info when the corresponding values haven't been set on `OpenshiftApplication`

**Comment by iocanel** [comment]
Should have been fixed in sundrio and ap4k has upgraded to the latest sundrio release. can you please check if this is still a thing?

**Comment by geoand** [comment]
I just confirmed that it works.

Thanks!
