### ISSUE TITLE
Add support for spring-cloud-kubernetes

### ISSUE THREAD

**Issue by iocanel** [ap4k/ap4k#204]
Generating resources required by sck like ServiceAccount, RoleBindings etc.

**Comment by iocanel** [comment]
Added, we need to document it and close the issue.

**Comment by iocanel** [comment]
@salaboy: Do you see anything additional required to do here?

So, far we generate ServiceAccount and Rolebinding. Do we need anything more?

**Comment by salaboy** [comment]
@iocanel so we need role, role binding and service account right? (plus the link of the service account in the deployment). 
It will be great if that is added if we detect in the classpath spring cloud Kubernetes libs. Is that the current behaviour? It will be great also to be able to have a flag to say if the Role and RoleBinding are Cluster wide or not. (ClusterRoleBinding, ClusterRole).

**Comment by iocanel** [comment]
@salaboy: At the moment we create the minium required resources when `sck` is found in the classpath. That is a service account and a rolebinding that gives the `view` role to the serviceaccount. Of course, the deployment will use the generated service account. This can't be cluster wide, as they require additional permission from the user.

**Comment by salaboy** [comment]
@iocanel that is good enough for me for now.. I can give it a try and see if works. The documentation needs to explain how to add the rights for accessing different resources.

**Comment by salaboy** [comment]
@iocanel do you know in which version is this available? so I can try it out?
