### ISSUE TITLE
Liveness and Readiness Probes And Spring Boot

### ISSUE THREAD

**Issue by ryanjbaxter** [ap4k/ap4k#223]
If Spring Boot Actuator is not on the class path and the `livenessProbe` and `readinessProbe` are not configured why are they added to the deployment yaml?  It can end up in Kubernetes thinking the app is down.

**Comment by iocanel** [comment]
My experience on the subject is that for web applications, its better to have a probe on the http port than nothing. 

For example, if you try to run automated tests without a probe at all, its most likely that it will fail, as the pod will appear as ready prematurely.

@ryanjbaxter: wdyt?

**Comment by ryanjbaxter** [comment]
@iocanel what does kubernetes do when a path is not specified in the probe?  Does it just hit the root of the app by default?  The root does not necessarily have to return anything.  I would think the functionality should be not added to the Deployment yaml unless specifically configured by the user or if we can detect that 1.) actuator is on the classpath then automatically configure it to hit /actuator/health.

**Comment by iocanel** [comment]
@ryanjbaxter: I think that it hits the root. That's not really a problem.
The problem that I see, is that its possible that the request perfromed has side-effects and could potentially be a source of problems.  So, I think that it should be changed as you suggest.

**Comment by ryanjbaxter** [comment]
@iocanel any idea when you will merge those changes into to master?

**Comment by iocanel** [comment]
As soon as I address the CI issues (a day or two).

**Comment by iocanel** [comment]
Meged, will release soon.
