### ISSUE TITLE
properties vs yaml for annotation-less mode?

### ISSUE THREAD

**Issue by metacosm** [ap4k/ap4k#232]
Is the support of properties on par with yaml when it comes to expressiveness of complex structures? Also, currently, only one file (`application.properties|yaml`) is affected by the annotation-less mode, at least as far as I can tell. Is this correct? If yes, this is an issue for Spring Boot for example since there might be multiple `application-*` files. How does `ap4k` deal with this case?

**Comment by iocanel** [comment]
Currently annotations, yaml and properties can do exactly the same stuff.

When multiple resources exist, they will be read in the following order:

application.propeties
application.yaml
application.yml
application-kubernetes.properties
application-kubernetes.yaml
application-kubernetes.yml

And create a single map, that is fed to ap4k.

So, things in the kubernetes profile may override stuff found in the default profile and so on.
