### ISSUE TITLE
[feature] Able to enable/disable to create k8s resources

### ISSUE THREAD

**Issue by cmoulliard** [ap4k/ap4k#37]
### Feature

As a user I want to have the possibility to enable / disable the generation of k8s yaml/json files when customResources are used as in this case, it makes more sense the install the custom resources such as Istio, Component CRD, ...

**Comment by iocanel** [comment]
As we made most annotations standalone (e.g. CompositeApplication doesn't require (KubernetesApplication), I think that we cover this issue.
