### ISSUE TITLE
Finalize annotation names

### ISSUE THREAD

**Issue by iocanel** [ap4k/ap4k#41]
There have been talks about the annotation names and how descriptive they are.

For example:
- KubernetesApplication
- OpenshiftApplication 

don't quite describe how they are used.

- SourceToImage
- DockerBuild

Neither describe nor provide the necessary context.

This issue is about discussing naming styles and alternatives:

1. Spring Boot sytle  
 
- KubernetesApplication
- OpenshiftApplication

It might doesn't describe the intention of generating resources, but then again I don't feel that it has too. `sundrio`, `immutables`, `lobmbok` and other projects that generate code, or perform bytecode manipulation don't use names that reflect that. Instead they use names that try to describe in a way the annotated class.

In the same sprit we could use the spring boot them and also go with:

- EnableS2iBuild
- EnableDockerBuild

For the sevice catalog I can't find an equivalent. But it could go like:

- WithServiceCatalog(instances = @ServiceInstance(...))

2. A diffrent take on Spring Boot style

- KubernetesResourceGenerationEnabled
- OpenshidtResourceGenerationEnabled

which is TOO long IMHO.

3. Descriptive names

- GenerateKubernetesResources 
- GenerateOpenshiftResources

4. Annotation combo:

- @Generate( kubernetes = @KubernetesResources(...))
- @Generate( openshift = @OpenshiftResources( ... )).

or a variation that doesn't have coupling with openshift, servicecatalog etc:

@Generate({@KubernetesResouces(...), @ServiceCatalogResource()).

Its not as simple as I would want.

**Comment by iocanel** [comment]
@cmoulliard @metacosm @gytis @geoand: additional suggestion or voting for one of those would really help.

**Comment by geoand** [comment]
Personally, I like having a verb in the annotation name. That way just looking at the annotation I pretty much know what to expect.

So I like things like `GenerateKubernetesResources` and `EnableS2iBuild`

**Comment by cmoulliard** [comment]
I like the idea to include a `verb` part of the annotation but I'm not sure that this is required/needed for the propositions such as `KubernetesResourceGenerationEnabled`, `EnableS2Build` as the annotation itself means that we `implicitly` enable the generation of resources.

The more `natural` annotation is this one `@generate( kubernetes = @KubernetesFilesResources(...))` as we not only document within the class what we are doing (= action, verb) but we also specify the type of resources that we will populate (files (yaml, json) for k8s, for OpenShift, for component CRD, ...).
I'm nevertheless concerned about the syntax to be included for such `combo` annotations which is really verbose, could be syntactically error prone and not very appealing for the developers.

As I don't think that we could, with one **magic word**, tries to express different concerns such as : 
- I want to generate Kubernetes | Openshift | Component | Istio resources (= Api + versions that I'm targetting)
- I want to populate Resources able to `Deploy` | `Build` the image on the kubernetes platform

then, we should perhaps investigate another solution where we combine : 

- An annotation to specify the model (= Api + version)
- Another to express the process (= Deployment, Build, ...)

This approach is also complex to validate/verify as some combinations will be supported while others make not sense

Examples

1. Generate Deployment resources using Kubernetes model
```
@KubernetesModel
@GenerateResources // By default we generate deployment resource
```
2. Generate DeploymentConfig resources using OpenShift model
```
@OpenshiftModel
@GenerateResources(process="deploy")
```
3. Generate Deployment & Build resources using OpenShift model
```
@OpenshiftModel
@GenerateResources(process="deploy,build")
```
4. Generate Component resource for a runtime using Component model
```
@ComponentModel // We will by default discover the runtime (vert.x, spring boot, thorntail,...) and generate a Component Runtime
```
5. Generate Component - Service resource using Component model
```
@ComponentModel
@ServiceCatalog
```
...

@iocanel @geoand @gytis @metacosm WDYT

**Comment by geoand** [comment]
I think that having to combine annotations like `KubernetesModel` and `@GenerateResources` would create more confusion so I would rather avoid it.
Also I have never been particularly fond of of combo annotations, but at least they are type safe and relatively easy to reason about.
If I had to choose between these two options, I would definitely choose the later

**Comment by iocanel** [comment]
I agree with @geoand on that `@KubernetesModel` and `@GenrateResources` would cause more confusion. As it brings straight ahead two questions:

1. what is the model?
2. what resources to generate?

I also strongly feel that the version of the platform is completely irrelevant with the annotation name. It could be a property but nothing more.

I want to make it as simple as it gets to get a user started, so I'd like to avoid using two annotations.

I am starting to lean towards:

@GenreateKubernetesManfiest
@GenerateOpenshifManifest

which is more accourate that the `@GenerateXXXResources` counterparts.

**Comment by cmoulliard** [comment]
I'm not opposite to use such annotations (even if I don't understand why we suffix the annotation name with Metadata)

```
@GenerateKubernetesManifest
@GenerateOpenshifManifest
```

but how do you plan to say that you would like to generate `Deploy` AND/OR `Build` resources ?

**Comment by iocanel** [comment]
@cmoulliard: For the build deploy thingy I thougt that we reached consensus on:

- EnableDockerBuild
- EnabledS2iBuild

This annotations may also include properties to mark that we want  `deploy` or `build`. But that for the biggest part should be controlled in the command line.

**Comment by iocanel** [comment]
And regarding the `metadata` suffix, its actually `manifest` which is a  tad more accurate than `resources`.

**Comment by cmoulliard** [comment]
Consensus's proposition to be voted

- Adopt `@GenerateYYYYYManifest` annotation to generate the associated resources which are for Kubernetes -> Deployment, OpenShift -> DeploymentConfig and for Custom Resource Definition, their corresponding resource (E.g Component runtime, ....)
- Use `EnableXXXXBuild` annotation responsible to create the resources needed to perform one of the Build's type supported (Docker, S2I,...).
- Pass an env/system property to the `mvn compile` command in order to deploy the resources

**Comment by geoand** [comment]
My 2 cents:

Use `Generate...` for the basics. 

I personally dont expect anything to be deployed unless I explicitly enable it on the command line - this is needed because I dont want every compilation to end up as a deployment

**Comment by cmoulliard** [comment]
I updated the proposition and replacing `Enable` with `Generate`

**Comment by iocanel** [comment]
Since we all agree on that I'll create a PR with those suggestions.

**Comment by iocanel** [comment]
In the docker build case we don't generate something. So `Enable` feels more natural.

**Comment by geoand** [comment]
But docker build should still controllable with a cli flag, right?

**Comment by iocanel** [comment]
yeah, we still need the annotation for customization etc.

**Comment by geoand** [comment]
Makes sense! :+1

**Comment by iocanel** [comment]
Since, we don't have an alternative naming proposal for the XXXApplication annotations, I will close it and reopen it if/when we have a concrete proposal.
