### ISSUE TITLE
build failing for the master branch, missing kubernetes config files

### ISSUE THREAD

**Issue by alexlungu10** [ap4k/ap4k#98]
Hello Team,
I want to run mvn install under the master branch and it seems that the build is failing, some files from the kubernetes/config path are missing.... maybe under windows, the generated-sources are not generated 100%
ap4k/core/src/main/java/io/ap4k/kubernetes/config/
![image](https://user-images.githubusercontent.com/32089110/50732187-456f8a00-117e-11e9-8dcb-55eb20542e3c.png)
The missing files are:
import io.ap4k.kubernetes.config.Annotation;
import io.ap4k.kubernetes.config.AwsElasticBlockStoreVolume;
import io.ap4k.kubernetes.config.AzureDiskVolume;
import io.ap4k.kubernetes.config.AzureFileVolume;
import io.ap4k.kubernetes.config.ConfigMapVolume;
import io.ap4k.kubernetes.config.Env;
import io.ap4k.kubernetes.config.KubernetesConfig;
import io.ap4k.kubernetes.config.Label;
import io.ap4k.kubernetes.config.Mount;
import io.ap4k.kubernetes.config.PersistentVolumeClaimVolume;
import io.ap4k.kubernetes.config.Port;
import io.ap4k.kubernetes.config.SecretVolume;

**Comment by iocanel** [comment]
@alexlungu10: The root cause is the same as the issue we discussed on Friday.
The code generators (sundrio) is not working as expected in windows due to the the slash issue. 

Need to cut a new sundrio release.

**Comment by iocanel** [comment]
@alexlungu10: it should work fine now. 

p.s: I do seem to have an encoding related issue when building the project on cmd.exe, but from IntelliJ it builds fine.
